sequence_dir: "/home/ssd_data/ROOT_KITTI/KITTI/dataset/sequences/"
dataset_config: "config/semantic-kitti-mos.yaml"
batch_size: 4
num_workers: 8
wandb_project: "LoRaMOS"

optimizer: "sgd"
lr: 0.02
momentum: 0.9
nesterov: True
weight_decay: 0.001

scheduler: "step"
begin_epoch: 0
pct_start: 0.01
step: 10
decay_factor: 0.5
epochs: 100