# ============================================================
# FarMOS Training Hyperparameters
# ============================================================

# Dataset
sequence_dir: "/home/ssd_data/ROOT_KITTI/KITTI/dataset/sequences/"
dataset_config: "config/semantic-kitti-mos.yaml"

# DataLoader
batch_size: 4
num_workers: 8

# Wandb
wandb_project: "FarMOS"

######################################################################
# Case 1: Standard Modern Setup (AdamW)
optimizer: "adamw"
lr: 0.001                # 1e-3
weight_decay: 0.01       # AdamW에서는 0.01 ~ 0.05 권장
scheduler: "cosine"
epochs: 100
######################################################################
# # Case 2: High Generalization Setup (SGD)
# optimizer: "sgd"
# lr: 0.01                 # SGD는 Adam보다 큰 lr 필요
# weight_decay: 0.0001     # 1e-4
# momentum: 0.9            # 필수 설정 (Nesterov 가속 효과)
# scheduler: "cosine"
# epochs: 100
######################################################################
# # Case 3: Stable Step-down Setup (Adam)
# optimizer: "adam"
# lr: 0.001
# weight_decay: 0.0001     # Adam은 L2 Regularization으로 동작
# scheduler: "step"
# step_size: 30            # 100 에폭 기준 30, 60, 90 지점에서 하락
# step_gamma: 0.1          # 1/10씩 lr 감소
# epochs: 100
######################################################################